feat: add lab to readme
morey-tech/managed-argocd-lab-template pull request #2
Opened 2022-11-16 00:53 UTC by morey-tech

2022-11-16 14:13 UTC, wojtekidd requested changes
Great stuff - added some newbie comments - tested on MacOS my Linux machine has problems with the internet again :/

2022-11-16 14:13 UTC, wojtekidd commented on README.md
> +11. Click "Create".
I had to delete one instance to add a new one since I had 3 already. There's a minimal chance this could happen to people - just letting you know.

2022-11-16 14:13 UTC, wojtekidd commented on README.md
> +    - This output assumes you are using `kind`.
This mentions using `kind` twice 
> if you're following using kid 

> this output assumes you're using kind

I think the first one is enough

2022-11-16 14:13 UTC, wojtekidd commented on README.md
> +   - Re-run the `get pods` command to check for updates on the pod statuses.
```suggestion
   - Re-run the `kubectl get pods -n akuity` command to check for updates on the pod statuses.
```

2022-11-16 14:13 UTC, wojtekidd commented on README.md
> +   - Re-run the `get pods` command to check for updates on the pod statuses.
This might be helpful to total newbies and later for people who go through the tutorial

2022-11-16 14:13 UTC, wojtekidd commented on README.md
> +5. Update `<environment-name>` in `spec.destination.name` to match your environment name (i.e., cluster name).
We're repeating the step here that we did on the very beginning of the steps - it created some confusion to me since I thought I need to do something I haven't yet done, so maybe let's stick to:
 
> Paste the contents of `apps/guestbook.yaml` from your repo (the one you've edited in the first steps of this tutorial)

?

2022-11-16 14:13 UTC, wojtekidd commented on README.md
> +7. In the top left, click "CREATE".
I couldn't create it without adding `PATH: guestbook`

2022-11-16 14:13 UTC, wojtekidd commented on README.md
> +4. In the top right, click "Commit changes...".
My `Commit changes...` was below the input box

2022-11-16 14:13 UTC, wojtekidd commented on README.md
> +2. Locate the `guestbook` deploy (i.e., Deployment) resource and click the three vertical dots on the right side of the card.
I'm a newbie, and I wasn't sure which `guestbook` you wanted me to locate - whether the MAIN one on the utmost left or any other one.

2022-11-16 14:13 UTC, wojtekidd commented on README.md
> +9.  To apply the changes, in the top bar, click "SYNC" then "SYNCHRONIZE".
This is very cool - please show in the webinar that you can enter this APP of APPS and have the whole entire other APP there

2022-11-16 14:30 UTC, morey-tech commented on README.md
> +2. Locate the `guestbook` deploy (i.e., Deployment) resource and click the three vertical dots on the right side of the card.
yeah, I was suspecting that might be an issue, I plan to add screenshots for clarity.

2022-11-16 14:40 UTC, morey-tech commented on README.md
> +5. Update `<environment-name>` in `spec.destination.name` to match your environment name (i.e., cluster name).
Ah yeah good point, now that the lad starts with updating those files I can remove the yaml here.

2022-11-16 14:41 UTC, morey-tech commented on README.md
> +7. In the top left, click "CREATE".
odd, the path is already in the yaml from the repo. Maybe this issue came from the confusion on the earlier step.

2022-11-16 14:44 UTC, morey-tech commented on README.md
> +4. In the top right, click "Commit changes...".
Strange, mine is not. Are you sure you're not confusing this commit changes with the one from step 6?

2022-11-16 16:07 UTC, wojtekidd approved these changes

2022-11-16 16:14 UTC, wojtekidd commented on README.md
> +## 2. Pre-requisetes
```suggestion
## 2. Pre-requisites
```

2022-11-16 21:06 UTC, morey-tech commented on README.md
> +## 2. Pre-requisetes
Apparently the consensus on the internet is `prerequisite` (no hyphen) so I'll fix that too

2022-11-16 21:08 UTC, morey-tech commented on README.md
> +4. In the top right, click "Commit changes...".
As discovered during our dry-run, the UI is different in come cases so I'll generalize this step

2022-11-17 12:25 UTC, wojtekidd approved these changes

2022-11-17 14:41 UTC, merged